In [222]:
import numpy as np
import casadi as ca

In [223]:
n = 3
a = np.ones([n,n])+1
a**3
# np.power(a,3)

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [224]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
print(np.multiply(x2, x2))

print(x1)
print(x2)

[0. 1. 4.]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[0. 1. 2.]


In [225]:
def cholesky_factorization_LDL(A):
    '''
    LDL.T form
    ''' 
    n = np.shape(A)[0]
    c = np.zeros([n,n])
#     l = np.zeros([n,n])
    l = np.diag([1]*n)
    d = np.zeros(n).reshape(-1,1)
    for j in range(n):
        if j == 0:
            c[j,j] = A[j,j] 
        else:
            c[j,j] = A[j,j] - l[j,:j] ** 2 @ d[:j,:] 
        d[j,:] =  c[j,j]
    
        if j == n-1:
            return l,d
        for i in range(j + 1, n):
#             print(j)
#             print(i)
            if j == 0:
                c[i,j] = A[i,j]
            else:
                print(j)
                c[i,j] = A[i,j] - (l[i,:j] * l[j,:j]) @ d[:j,:] 
                print( d[:j,:])
            l[i,j] = c[i,j] / d[j,:] 
#             print(l[i,j])
    return l,d

In [226]:
def cholesky_factorization_LL(A):
    '''
    LL.T form
    ''' 
    n = np.shape(A)[0]
    c = np.zeros([n,n])
#     l = np.zeros([n,n])
    l = np.diag([1]*n)
    d = np.zeros(n).reshape(-1,1)
    for j in range(n):
        if j == 0:
            c[j,j] = A[j,j] 
        else:
            c[j,j] = A[j,j] - l[j,:j] ** 2 @ d[:j,:] 
        d[j,:] =  c[j,j]
    
        if j == n-1:
            return l,d
        for i in range(j + 1, n):
#             print(j)
#             print(i)
            if j == 0:
                c[i,j] = A[i,j]
            else:
                print(j)
                c[i,j] = A[i,j] - (l[i,:j] * l[j,:j]) @ d[:j,:] 
                print( d[:j,:])
            l[i,j] = c[i,j] / d[j,:] 
#             print(l[i,j])
    return l,d

In [227]:
L = np.array([[1,0,0],[3,1,0],[3,3,1]])
D = np.diag([9,9,9])
A = L @ D @ L.T
A

array([[  9,  27,  27],
       [ 27,  90, 108],
       [ 27, 108, 171]])

In [228]:
L @ np.diag([3,3,3])

array([[3, 0, 0],
       [9, 3, 0],
       [9, 9, 3]])

In [229]:
L = np.linalg.cholesky(A)
L

array([[3., 0., 0.],
       [9., 3., 0.],
       [9., 9., 3.]])

In [230]:
cholesky_factorization_LDL(A)

1
[[9.]]


(array([[1, 0, 0],
        [3, 1, 0],
        [3, 3, 1]]),
 array([[9.],
        [9.],
        [9.]]))

In [231]:
L = np.array([[1,0,0],[2,3,0],[3,2,1]])
D = np.diag([-10,9,9])
A = L @ D @ L.T

cholesky_factorization_LDL(A)

1
[[-10.]]


(array([[1, 0, 0],
        [2, 1, 0],
        [3, 0, 1]]),
 array([[-10.],
        [ 81.],
        [ 45.]]))